# Generated by Django 3.0.6 on 2020-05-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单编号')),
                ('order_status', models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成'), (3, '已挂起')], default=0, verbose_name='订单状态')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='数量')),
                ('delivery_time', models.DateField(verbose_name='交付时间')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_manager.ProductModel', verbose_name='产品')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(help_text='本行为系统自动创建', max_length=30, unique=True, verbose_name='VIN')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_manager.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '产品记录',
                'verbose_name_plural': '产品记录',
            },
        ),
        migrations.CreateModel(
            name='ProductRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.SmallIntegerField(default=0, verbose_name='工序顺序号')),
                ('step_name', models.CharField(max_length=100, unique=True, verbose_name='工序名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_manager.Product', verbose_name='对应产品')),
            ],
            options={
                'verbose_name': '产品过程记录',
                'verbose_name_plural': '产品过程记录',
            },
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=30, verbose_name='VIN')),
                ('total_result', models.BooleanField(default=False, verbose_name='总结果')),
                ('item_name', models.CharField(max_length=100, unique=True, verbose_name='测试项名称')),
                ('item_result', models.BooleanField(default=False, verbose_name='测试项结果')),
                ('item_data', models.CharField(max_length=100, verbose_name='测试项数据')),
                ('item_upper', models.CharField(max_length=100, verbose_name='测试标准上限')),
                ('item_lower', models.CharField(max_length=100, verbose_name='测试标准下限')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('product_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_manager.ProductRecord', verbose_name='产品过程记录')),
            ],
            options={
                'verbose_name': '测试记录',
                'verbose_name_plural': '测试记录',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True, verbose_name='序列号')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已装配')),
                ('iqc_checked', models.BooleanField(default=False, verbose_name='是否IQC检验')),
                ('batch_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='批次号')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('product_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_manager.ProductRecord', verbose_name='产品过程记录')),
            ],
            options={
                'verbose_name': '物料信息',
                'verbose_name_plural': '物料信息',
            },
        ),
        migrations.CreateModel(
            name='IqcRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, verbose_name='序列号')),
                ('total_result', models.BooleanField(default=False, verbose_name='总结果')),
                ('item_name', models.CharField(max_length=100, unique=True, verbose_name='测试项名称')),
                ('item_result', models.BooleanField(default=False, verbose_name='测试项结果')),
                ('item_data', models.CharField(max_length=100, verbose_name='测试项数据')),
                ('item_upper', models.CharField(max_length=100, verbose_name='测试标准上限')),
                ('item_lower', models.CharField(max_length=100, verbose_name='测试标准下限')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_manager.Material', verbose_name='所属物料')),
            ],
            options={
                'verbose_name': '检验记录',
                'verbose_name_plural': '检验记录',
            },
        ),
    ]
