# Generated by Django 3.0.7 on 2020-07-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='订单编号'),
        ),
    ]
