# Generated by Django 3.0.6 on 2020-05-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_version', models.CharField(max_length=30, verbose_name='BOM版本')),
                ('name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('erp_no', models.CharField(max_length=30, unique=True, verbose_name='物料号')),
                ('quantity', models.FloatField(verbose_name='用量')),
                ('is_traced', models.BooleanField(default=False, verbose_name='是否追溯')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_manager.ProductModel', verbose_name='产品型号')),
            ],
            options={
                'verbose_name': '物料型号',
                'verbose_name_plural': '物料型号',
                'unique_together': {('product_model', 'bom_version')},
            },
        ),
    ]
