# Generated by Django 3.0.7 on 2020-07-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_version', models.CharField(max_length=30, verbose_name='BOM版本')),
                ('name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='型号描述')),
                ('erp_no', models.CharField(max_length=30, verbose_name='物料号')),
                ('category', models.SmallIntegerField(choices=[(0, '无'), (1, '钣金零件'), (2, '底盘总成'), (3, '电子电气'), (4, '金属标件'), (5, '塑料标件'), (6, '塑料零件'), (7, '其他')], default=0, verbose_name='类别')),
                ('quantity', models.FloatField(verbose_name='用量')),
                ('is_traced', models.BooleanField(default=False, verbose_name='是否追溯')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_manager.ProductModel', verbose_name='产品型号')),
            ],
            options={
                'verbose_name': '物料型号',
                'verbose_name_plural': '物料型号',
                'unique_together': {('product_model', 'erp_no')},
            },
        ),
    ]
