# Generated by Django 3.0.7 on 2020-07-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmodel',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '钣金零件'), (2, '底盘总成'), (3, '电子电气'), (4, '金属标件'), (5, '塑料标件'), (6, '塑料零件'), (7, '其他')], default=0, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='materialmodel',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='型号描述'),
        ),
    ]
