# Generated by Django 3.0.7 on 2020-07-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_manager', '0002_auto_20200711_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmodel',
            name='erp_no',
            field=models.CharField(max_length=30, verbose_name='物料号'),
        ),
    ]
