# Generated by Django 3.0.7 on 2020-07-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_productmodel_bom_version'),
        ('bom_manager', '0002_auto_20200703_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialmodel',
            unique_together={('product_model', 'erp_no')},
        ),
    ]
