# Generated by Django 3.0.6 on 2020-05-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_manager', '0001_initial'),
        ('station_manager', '0001_initial'),
        ('bom_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100, unique=True, verbose_name='工序名称')),
                ('sequence_no', models.SmallIntegerField(default=0, verbose_name='工序顺序号')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('product_model', models.ManyToManyField(blank=True, to='product_manager.ProductModel', verbose_name='所属产品')),
                ('relate_material', models.ManyToManyField(blank=True, to='bom_manager.MaterialModel', verbose_name='关联物料')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station_manager.Station', verbose_name='工站')),
            ],
            options={
                'verbose_name': '生产过程',
                'verbose_name_plural': '生产过程',
            },
        ),
    ]
