# Generated by Django 3.0.7 on 2020-09-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_manager', '0001_initial'),
        ('bom_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='product_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_manager.ProductModel', verbose_name='产品型号'),
        ),
        migrations.AlterUniqueTogether(
            name='materialmodel',
            unique_together={('is_delete', 'erp_no')},
        ),
        migrations.AlterUniqueTogether(
            name='inspection',
            unique_together={('is_delete', 'num'), ('is_delete', 'name')},
        ),
    ]
