# Generated by Django 3.0.7 on 2020-08-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_productmodel_process_route'),
        ('bom_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='product_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_manager.ProductModel', verbose_name='产品型号'),
        ),
    ]
