# Generated by Django 3.0.7 on 2020-08-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_manager', '0001_initial'),
        ('process_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station_manager.Fixture', verbose_name='工装'),
        ),
    ]
