# Generated by Django 3.0.7 on 2020-09-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sequence_no', models.SmallIntegerField(verbose_name='工序顺序号')),
                ('result', models.SmallIntegerField(blank=True, choices=[(0, 'Fail'), (1, 'Pass')], default=None, null=True, verbose_name='结果')),
            ],
            options={
                'verbose_name': '产品过程记录',
                'verbose_name_plural': '产品过程记录',
                'db_table': 'sm_process_record',
            },
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('num', models.SmallIntegerField(verbose_name='测试项编号')),
                ('name', models.CharField(max_length=100, verbose_name='测试项名称')),
                ('result', models.SmallIntegerField(choices=[(0, 'Fail'), (1, 'Pass')], verbose_name='测试项结果')),
                ('data', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='测试项数据')),
                ('process_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProcessRecord', verbose_name='产品过程记录')),
            ],
            options={
                'verbose_name': '测试项记录',
                'verbose_name_plural': '测试项记录',
                'db_table': 'sm_test_record',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('vin', models.CharField(help_text='本行为系统自动创建', max_length=30, verbose_name='VIN')),
                ('order_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_manager.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '产品记录',
                'verbose_name_plural': '产品记录',
                'db_table': 'sm_product',
                'unique_together': {('is_delete', 'vin')},
            },
        ),
        migrations.AddField(
            model_name='processrecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.Product', verbose_name='对应产品'),
        ),
        migrations.CreateModel(
            name='AssemblyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sn', models.CharField(max_length=30, verbose_name='SN')),
                ('process_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProcessRecord', verbose_name='所属工序')),
            ],
            options={
                'verbose_name': '装配记录',
                'verbose_name_plural': '装配记录',
                'db_table': 'sm_assembly_record',
                'unique_together': {('is_delete', 'sn')},
            },
        ),
    ]
