# Generated by Django 3.0.7 on 2020-08-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_manager', '0002_productmodel_process_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='客户编号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='客户名称')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('contact', models.CharField(max_length=100, verbose_name='联系人')),
                ('tel', models.CharField(max_length=20, verbose_name='电话')),
                ('zip_code', models.CharField(max_length=20, verbose_name='邮编')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('num', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='订单编号')),
                ('status', models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成'), (3, '已挂起')], default=0, verbose_name='订单状态')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='数量')),
                ('delivery_time', models.DateField(verbose_name='交付时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_manager.Customer', verbose_name='客户')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_manager.ProductModel', verbose_name='产品')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
    ]
