# Generated by Django 3.0.6 on 2020-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_no', models.CharField(blank=True, help_text='本行为系统自动创建', max_length=32, null=True, verbose_name='工站编号')),
                ('station_name', models.CharField(max_length=100, verbose_name='工站名称')),
                ('station_category', models.SmallIntegerField(choices=[(0, '无'), (1, '来料检验（无VIN）'), (2, '测试设备（无VIN）'), (3, '测试设备'), (4, '组装'), (5, '过程检验'), (6, '成品检验'), (7, '入库')], default=0, verbose_name='工位类型')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '工站信息',
                'verbose_name_plural': '工站信息',
            },
        ),
    ]
