# Generated by Django 3.0.7 on 2020-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='bom_version',
            field=models.CharField(default='V1.00', max_length=10, verbose_name='BOM版本'),
        ),
    ]
