# Generated by Django 3.0.7 on 2020-09-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('batch_num', models.CharField(max_length=20, verbose_name='批次号')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='来料总数量')),
                ('qualified_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='来料合格数量')),
                ('used_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='使用数量')),
            ],
            options={
                'verbose_name': '一般物料信息',
                'verbose_name_plural': '一般物料信息',
                'db_table': 'sm_general_material',
            },
        ),
        migrations.CreateModel(
            name='GMInspectRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('num', models.CharField(max_length=20, verbose_name='检验项编号')),
                ('name', models.CharField(max_length=20, verbose_name='检验项名称')),
                ('qualified_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='检验项合格数量')),
                ('data', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='检验项数据')),
            ],
            options={
                'verbose_name': '一般物料检测项',
                'verbose_name_plural': '一般物料检测项',
                'db_table': 'sm_gminspect_record',
            },
        ),
        migrations.CreateModel(
            name='TMInspectRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('num', models.CharField(max_length=20, verbose_name='检验项编号')),
                ('name', models.CharField(max_length=20, verbose_name='检验项名称')),
                ('result', models.SmallIntegerField(choices=[(0, 'Fail'), (1, 'Pass')], default=0, verbose_name='检验项结果')),
                ('data', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='检验项数据')),
            ],
            options={
                'verbose_name': '追溯物料检测项',
                'verbose_name_plural': '追溯物料检测项',
                'db_table': 'sm_tminspect_record',
            },
        ),
        migrations.CreateModel(
            name='TraceMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.SmallIntegerField(choices=[(0, '未检验'), (1, '检验中'), (2, '检验OK'), (3, '检验NG')], default=0, verbose_name='检验状态')),
                ('sn', models.CharField(max_length=30, verbose_name='SN')),
                ('is_used', models.SmallIntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0, verbose_name='是否使用')),
                ('batch_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='批次号')),
            ],
            options={
                'verbose_name': '追溯物料信息',
                'verbose_name_plural': '追溯物料信息',
                'db_table': 'sm_trace_material',
            },
        ),
    ]
