# Generated by Django 3.0.7 on 2020-09-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bom_manager', '0001_initial'),
        ('Inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracematerial',
            name='material_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bom_manager.MaterialModel', verbose_name='所属物料型号'),
        ),
        migrations.AddField(
            model_name='tminspectrecord',
            name='trace_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inspection.TraceMaterial', verbose_name='所属一般物料'),
        ),
        migrations.AddField(
            model_name='gminspectrecord',
            name='general_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inspection.GeneralMaterial', verbose_name='所属一般物料'),
        ),
        migrations.AddField(
            model_name='generalmaterial',
            name='material_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bom_manager.MaterialModel', verbose_name='所属物料型号'),
        ),
    ]
